### ISSUE TITLE
getExePath() fails when MSTest.exe exists

### ISSUE THREAD

**Issue by jstevensonhoare** [mrjackdavis/grunt-mstest#3]
I have VS2010 installed and VS2013 (Express for Web). The latter causes the <code>process.env.VS120COMNTOOLS</code> to be defined, and the former <code>process.env.VS100COMNTOOLS</code>. Unfortunately, VS2013 (Express for Web) does not install MSTest.exe although VS2010 does.

The code in <code>getExePath()</code> stops if the first defined VS folder does not contain MSTest.exe even though it exists in an 'earlier' version.

It would be beneficial if the code checked all folders.

Also note that defining <code>mstestPath</code> in the task- or target-level options (as suggested in the fatal error message) does not help as the call is currently always made to <code>getExePath()</code>. I am not a JS expert but if you changed line https://github.com/mrjackdavis/grunt-mstest/blob/master/tasks/mstest.js#L25 to read

<code>mstestPath: grunt.option('mstestPath') || getExePath(),</code>

then wouldn't this only invoke the function if <code>mstestPath</code> was not already defined?

**Comment by mrjackdavis** [comment]
Hi @jstevensonhoare, I expect I'll have a chance to look into this on the weekend. If it's urgent you could make the change yourself and create a pull request.

**Comment by mrjackdavis** [comment]
I have not the time to take a look at this. It's also been a long while since I've used this repository.

If you'd like to implement these changes yourself, I'd be happy to merge a pull request

**Comment by mscheepers** [comment]
Solved a long time ago...
