### ISSUE TITLE
grunt-mstest Failing with Visual Studio 2015

### ISSUE THREAD

**Issue by cdalto** [mrjackdavis/grunt-mstest#5]
mstest is failing when trying to perform 'grunt release' on a repository that I'm working in. The issue seems to be related to the fact that Visual Studio 2015 now uses a new environment variable for visual studio tools, VS140COMNTOOLS.

**Comment by mrjackdavis** [comment]
Hi @cdalto, I'm not actively maintaining this repo at the moment. If you'd like to solve this issue yourself, please submit a PR. Thanks

**Comment by cdalto** [comment]
I've actually got a solution. I'll submit a pull request as soon as possible.

**Comment by mscheepers** [comment]
Hi @cdalto, I just closed the issue because it was solved in version 1.0.5. Thanks

**Comment by cdalto** [comment]
Thanks for the commit! I was away from my computer over the holidays and unable to commit the exact same fix. :)

**Comment by cdalto** [comment]
@mscheepers, do you happen to know why `npm install grunt-mstest@0.1.6 --save-dev`
throws the error:

> version not found: grunt-mstest@0.1.6

**Comment by cdalto** [comment]
Sorry to be incessant, but the latest package just needs to be published to npm. I tried doing this myself, but someone with the right permissions will have to do it.

**Comment by mrjackdavis** [comment]
Hi all, I've published `0.1.6` to npm. I've also given @mscheepers access for any future needs.
